apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.username }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.password }}