apiVersion: batch/v1
kind: Job
metadata:
  name: create-minio-bucket
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio:9000 {{ .Values.minio.username }} {{ .Values.minio.password }}; do
                sleep 2
              done

              mc mb --ignore-existing local/{{ .Values.minio.bucket }}